# These are the general script settings. I put settings here that will likely not change each time you use the script.

settings:

  # ======================================
  # Settings for new_video_project.command
  # ======================================

  # What is the name of your video editor?
  # Options: Premiere, FCPX, Sony Vegas, etc.
  editor: Premiere

  # What is the name of your motion graphics application?
  # Options: After Effects, Motion, etc.
  motion_graphics: After Effects

  # What is the name of your audio application?
  # Options: Audition, etc.
  audio: Audition

  # What is the name of your coloring application?
  # Options: Resolve, Speed Grade, etc.
  coloring: Resolve

  # Create folders for source and proxy footage?
  # Options: true, false
  create_proxy_folders: true

  # ====================================
  # Settings for video_ingestion.command
  # ====================================

  # Do you want to copy the file or move the file? Moving means deleting from original folder
  # Options: copy, move
  # WARNING: DO NOT use the "move" method when transferring files from an SD card.
  move_type: move


  # Do you want to move video files into a folder by the name of your camera?
  # Options: true, false
  move_footage_to_camera_folder: true


  # Do you want to further split videos into folders based on video resolution?
  # Options: true, false
  split_footage_by_resolution: true


  # Do you want to rename files with date stamp and camera name? Example renaming: 12_31_16_MarkIII_0.MOV
  # Options: true, false
  rename_files_by_datestamp_and_camera: true


  # Do you want to see a preview of the renamed files before proceeding?
  # Options: true, false
  show_rename_preview: true